feat: fulfillRand func + renaming vars
samhatem/nakamotOs-core pull request #1
Opened 2021-05-15 22:52 UTC by christian-miljkovic

Updates to NakamotosERC20.sol

2021-05-17 04:16 UTC, samhatem requested changes

2021-05-17 04:16 UTC, samhatem commented on tasks/start-lottery.ts
> +        const amount = ethers.utils.hexlify(ethers.constants.WeiPerEther);
amount should be configureable because it's different on different networks.

Also I'd recommend using BigNumber instead of treating amount as a hex string. ethers.constants.WeiPerEther is likely already a big number and ethers.js contract calls can handle uint256 (and other numbers) as BigNumber

2021-05-17 04:16 UTC, samhatem commented on tasks/start-lottery.ts
> +        const linkTokenAddress = networkParams.linkToken || taskArgs.linkaddress;
why not just required the linkToken is in the network params?

This is also a little unintuitive because someone using this task would expect that a param they set would be used but if link token is set in network config then that's used instead.

In my opinion it's probably easiest to require the linkAddress is in the network config because this task can only be called on specific networks anyways

2021-05-17 04:16 UTC, samhatem commented on tasks/start-lottery.ts
> +        console.log("result", result);
nit pick but not a huge fan of mixing async/await and callbacks. Makes the code hard to understand.

async/await and try/catch is the standard in typescript as it's more readable

2021-05-17 04:16 UTC, samhatem commented on tsconfig.json
> +        "helper-hardhat-config.ts",
if you move this file to config then also remove it from here

2021-05-17 14:03 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
> +pragma solidity <0.8.0;
thats so that safemath is built in, I was getting errors when trying to compile the contracts such as this:

```
TypeError: Member “add” not found or not visible after argument-dependent lookup in uint256
```

2021-05-17 14:04 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
> +            ownerTicketCount[_msgSender()] = ownerTicketCount[_msgSender()] + ticketsCreated;
see comment above - but mainly I was getting compile errors when using safeMath

2021-05-17 14:05 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
> +    function expand(uint256 randomValue) public view returns (uint256[] memory expandedValues) {
When compiling there was an error because this line `expandedValues = new uint256[](maxNFTSupply)` saying that I needed to change to `view`

2021-05-17 14:06 UTC, christian-miljkovic commented on helper-hardhat-config.ts
> +interface networkInterface {
I was copying this from an example I was using here: https://github.com/smartcontractkit/hardhat-starter-kit

2021-05-17 14:53 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
I thought that when the block number is greater than the `lottoBlock` then it has already been started - I might be missing something

2021-05-17 14:54 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
OH hasn't started already aka `block.number < lottoBlock`

2021-05-17 14:55 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
why don't we just do `require(block.number == lottoBlock)`

2021-05-17 14:56 UTC, christian-miljkovic commented on helper-hardhat-config.ts
> +interface networkInterface {
will just move to config

2021-05-17 14:57 UTC, christian-miljkovic commented on tasks/start-lottery.ts
> +        console.log("result", result);
agreed, following along with that task example I linked before, this code is still work in progress but will change

2021-05-17 19:58 UTC, samhatem commented on contracts/NakamotOsERC20.sol
> why don't we just do `require(block.number == lottoBlock)`

what happens if we submit a transactions and it's not picked up in the lottoBlock?

2021-05-17 19:59 UTC, samhatem commented on contracts/NakamotOsERC20.sol
also what happens if after we start the lotto, someone else sends LINK to the contract and calls this function again?

2021-05-17 20:09 UTC, samhatem commented on contracts/NakamotOsERC20.sol
> +    function expand(uint256 randomValue) public view returns (uint256[] memory expandedValues) {
looks like you're right, that function should be pure

2021-05-17 20:11 UTC, samhatem commented on contracts/NakamotOsERC20.sol
> +pragma solidity <0.8.0;
safemath is built-in in >=0.8.0 and this is <0.8.0

this error means there's multiple versions of safemath

2021-05-17 20:14 UTC, samhatem commented on tasks/start-lottery.ts
> +        const LinkToken = await ethers.getContractFactory("LinkToken");
we can get rid of the LinkToken contract because all we're using it for is to get it's abi which will be the same as any other erc20 token abi

2021-05-17 20:19 UTC, samhatem commented on contracts/NakamotOsERC20.sol
to clarify, it's not guaranteed that a transaction to start the lottery will be picked up in an exact block which would mean the lottery could never take place.

We also need to guarantee that only 1 lottery can ever be created. If someone else can call `startLottery` a second time then 10 additional NFTs would be created

2021-05-18 02:35 UTC, christian-miljkovic commented on contracts/NakamotOsERC20.sol
> +            ownerTicketCount[_msgSender()] = ownerTicketCount[_msgSender()].add(ticketsCreated);
@samhatem getting this error when I try to compile:

```
TypeError: Member "add" not unique after argument-dependent lookup in uint256
```

2021-05-19 14:39 UTC, samhatem requested changes

2021-05-19 14:39 UTC, samhatem commented on test/NakamotOsERC20.test.ts
> +        });
test should check values of `ticketCount`, `ticketToOwner`, and `ownerTicketCount`

2021-05-19 14:39 UTC, samhatem commented on test/NakamotOsERC20.test.ts
> +        });
same as above

2021-05-19 14:39 UTC, samhatem commented on test/NakamotOsERC20.test.ts
> +});
need tests for burning less than 1 token and burning tokens after the lottery and making sure the contract performs as expected

2021-05-19 14:39 UTC, samhatem commented on test/NakamotOsERC20.test.ts
> +});
Also need tests for the lottery on chainlink

2021-05-21 02:43 UTC, christian-miljkovic commented on test/NakamotOsERC20.test.ts
> +/* eslint-disable func-names */
this is just putting this in a test folder

2021-05-21 12:05 UTC, samhatem approved these changes

2021-05-21 12:05 UTC, merged